### Added names specific to my project (Normal, TissueType, )
bresect.name.map <- c(
                      ## datasets
                      validation.gq="Validation Set",
                      validation="Validation Set - MGGQ",
                      testset="Discovery Set",
                      discovery="VVL",
                      union="ExpC",

                      anders="AND",
                      bild="BLD",
                      boersma.epi="BOTE",
                      boersma.stroma="BOTS",
                      curtis="MTBC",
                      curtis.discovery="MTBCd",
                      curtis.discovery.1="MTBCd1",
                      curtis.discovery.2="MTBCd2",
                      curtis.validation="MTBCv",
                      curtis.validation.1="MTBCv1",
                      curtis.validation.2="MTBCv2",
                      guedj="GDJ",
                      jonsson="JON",
                      li="LI",
                      mcgill.epi="MGTE",
                      mcgill.gq="MGGQ",
                      mcgill.str="MGTS",
                      muggerud="MUG",
                      nki="NKI",
                      parker="PKR",
                      servant="SER",
                      sotiriou="SOT",
                      tcga="TCGA",
                      vanvliet="VVL",
                      wang="WNG",
                      
                      ## blood datasets
                      cc1.blood="cc1.blood",
                      cc2.blood="cc2.blood",
                      cc3.blood="cc3.blood",
                      cc4.blood="cc4.blood",
                      cc.blood="cc1.cc2.blood",
                      biopsy="biopsy",

                      ##  cohorts
                      all="Unstratified",
                      erp="ER+",
                      ern="ER-",
                      her2clinicalp="HER2+",
                      her2clinicaln="HER2-",
                      her2clinicalp.erp="ER+/HER2+",
                      her2clinicalp.ern="ER-/HER2+",
                      her2clinicaln.erp="ER+/HER2-",
                      her2clinicaln.ern="ER-/HER2-",
                      luma="lumA",
                      luma.erp="ER+/lumA",
                      lumb="lumB",
                      lumb.erp="ER+/lumB",
                      normal="normL",
                      normal.erp="ER+/normL",
                      basal="basalL",
                      basal.erp="ER+/basalL",
                      basal.ern="ER-/basalL",
                      her2pam50p="her2E",
                      her2pam50p.erp="ER+/her2E",
                      her2pam50p.ern="ER-/her2E",
                      her2pam50p.her2clinicalp="her2E/HER2+",
                      her2pam50p.her2clinicaln="her2E/HER2-",
                      her2pam50p.her2clinicalp.erp="ER+/her2E/HER2+",
                      her2pam50p.her2clinicalp.ern="ER-/her2E/HER2+",
                      her2pam50p.her2clinicaln.erp="ER+/her2E/HER2-",
                      her2pam50p.her2clinicaln.ern="ER-/her2E/HER2-",
                      her2pam50n="her2E-",
                      her2pam50n.erp="ER+/her2E-",
                      her2pam50n.ern="ER-/her2E-",
                      auth.luma="lumA(MTBC)",
                      auth.luma.erp="ER+/lumA(MTBC)",
                      auth.lumb="lumB(MTBC)",
                      auth.lumb.erp="ER+/lumB(MTBC)",
                      auth.normal="normL(MTBC)",
                      auth.normal.erp="ER+/normL(MTBC)",
                      auth.basal="basalL(MTBC)",
                      auth.basal.erp="ER+/basalL(MTBC)",
                      auth.basal.ern="ER-/basalL(MTBC)",
                      auth.her2pam50p="her2E(MTBC)",
                      auth.her2pam50p.erp="ER+/her2E(MTBC)",
                      auth.her2pam50p.ern="ER-/her2E(MTBC)",
                      auth.her2pam50p.her2clinicalp="her2E(MTBC)/HER2+",
                      auth.her2pam50p.her2clinicaln="her2E(MTBC)/HER2-",
                      auth.her2pam50p.her2clinicalp.erp="ER+/her2E(MTBC)/HER2+",
                      auth.her2pam50p.her2clinicalp.ern="ER-/her2E(MTBC)/HER2+",
                      auth.her2pam50p.her2clinicaln.erp="ER+/her2E(MTBC)/HER2-",
                      auth.her2pam50p.her2clinicaln.ern="ER-/her2E(MTBC)/HER2-",
                      auth.her2pam50n="her2E(MTBC)-",
                      auth.her2pam50n.erp="ER+/her2E(MTBC)-",
                      auth.her2pam50n.ern="ER-/her2E(MTBC)-",

                      LumA="lumA",
                      LumB="lumB",
                      Basal="basalL",
                      Normal="normL",
                      Her2="her2E",

                      intclust1="IntClust1",
                      intclust2="IntClust2",
                      intclust3="IntClust3",
                      intclust4="IntClust4",
                      intclust5="IntClust5",
                      intclust6="IntClust6",
                      intclust7="IntClust7",
                      intclust8="IntClust8",
                      intclust9="IntClust9",
                      intclust10="IntClust10",

                      UNS="UNS", BL1="BL1", BL2="BL2", IM="IM",
                      M="M", MSL="MSL", LAR="LAR",

                      basL="basL",lumA="lumA",lumB="lumB",
                      normL="normL",lumC="lumC",mApo="mApo",

                      ## My variables
                      Normal="Matched control",
                      TissueType="Tissue type",
                      
                      ## clinical variables
                      event.5="Outcome (5yrs)",
                      event="Outcome",
                      lymph="Lymph node status",
                      type="Tumor type",
                      age="Age",
                      size="Tumor size",
                      er="ER status",
                      her2="HER2 status",
                      stage="Tumor stage",
                      grade="Tumor grade",
                      pam50.genefu="PAM50 (genefu)",
                      pam50.parker="PAM50 (parker)",
                      hybrid.genefu="hybrid",
                      lum="luminal subtypes",
                      lumN="luminal & normal-like subtypes",
                      prolif="proliferative subtypes",
                      basalL="basal-like subtype",
                      MKS="Mitotic Kinase Score",
                      ERS="Estrogen Receptor Score",
                      LUMS="Luminal Score",
                      HER2S="Her2 Score",
                      aims="AIMS",
                      intclust="IntClust",
                      cit="CIT Subtype",
                      lehmann="TNBC Subtype",
                      claudin.low="Claudin-low",
                      chemo="Chemotherapy",
                      tamoxifen="Tamoxifen",
                      herceptin="Herceptin",
                      dataset="Dataset",
                      orig.dataset="Blood dataset",
                      TissueType="Tissue type", #et:biopsy ; st:blood from bc ; sn:blood from controls
                      consistently.classified="Consistenty classified",
                      ccgc="Consistently classified as good correctly",
                      ccgi="Consistently classified as good incorrectly",
                      ccbc="Consistently classified as bad correctly",
                      ccbi="Consistently classified as bad incorrectly",
                      ncc="Not consistently classified",
                      hospital="hospital",
                      bmi="bmi",
                      weight="weight",
                      menopause="menopause",
                      weight.70.plus="weigth > 70 kg",
                      age.55.plus="age > 55",
                      hrt="hormone therapy use",
                      medication="medication use",
                      smoking="current smoker",

                      ## performance measures
                      fisher="-log10(Fisher)",
                      acc="Accuracy",
                      acc.good="Accuracy within good",
                      acc.bad="Accuracy within bad",
                      acc.prod="PoA",
                      pv.good="Predictive value of good",
                      pv.bad="Predictive value of bad",
                      f05.good="F_0.5 measure (wrt good)",
                      f1.good="F_1 measure (wrt good)",
                      f2.good="F_2 measure (wrt good)",
                      f05.bad="F_0.5 measure (wrt bad)",
                      f1.bad="F_1 measure (wrt bad)",
                      f2.bad="F_2 measure (wrt bad)",
                      mcc="MCC",
                      auc="AUC",
                      coxph="-log10(coxph)")

bresect.cohorts.lehmann <- c(UNS="UNS", BL1="BL1", BL2="BL2", IM="IM", M="M", MSL="MSL", LAR="LAR")
bresect.cohorts.cit <- c(basL="basL",lumA="lumA",lumB="lumB", normL="normL",lumC="lumC",mApo="mApo")


bresect.datasets.canonical <- c("bild", "curtis.discovery", "curtis.validation", "guedj", "li", "nki", "parker", "servant", "sotiriou", "vanvliet", "wang")

bresect.cohorts <- c("all",
                     "erp",
                     "ern",
                     "her2clinicalp",
                     "her2clinicaln",
                     "her2clinicalp.erp",
                     "her2clinicalp.ern",
                     "her2clinicaln.erp",
                     "her2clinicaln.ern",
                     "luma",
                     "lumb",
                     "normal",
                     "normal.erp",
                     "basal",
                     "basal.erp",
                     "basal.ern",
                     "her2pam50p",
                     "her2pam50p.erp",
                     "her2pam50p.ern",
                     "her2pam50p.her2clinicalp",
                     "her2pam50p.her2clinicaln",
                     "her2pam50p.her2clinicalp.erp",
                     "her2pam50p.her2clinicalp.ern",
                     "her2pam50p.her2clinicaln.erp",
                     #"her2pam50p.her2clinicaln.ern",
                     "her2pam50n",
                     "her2pam50n.erp",
                     "her2pam50n.ern")

bresect.cohorts.canonical <- c("all",
                               "erp",
                               "ern",
                               "her2clinicalp",
                               "her2clinicalp.ern",
                               "her2clinicalp.erp",
                               "her2clinicaln.ern",
                               "luma",
                               "lumb",
                               "normal",
                               "her2pam50p",
                               "basal",
                               "her2pam50p.ern",
                               "her2pam50p.erp",
                               "basal.ern",
                               "basal.erp")

bresect.cohorts.canonical.auth <- c("all",
                                    "erp",
                                    "ern",
                                    "her2clinicalp",
                                    "her2clinicalp.ern",
                                    "her2clinicalp.erp",
                                    "her2clinicaln.ern",
                                    "auth.luma",
                                    "auth.lumb",
                                    "auth.normal",
                                    "auth.normal.erp",
                                    "auth.her2pam50p",
                                    "auth.basal",
                                    "auth.her2pam50p.ern",
                                    "auth.her2pam50p.erp",
                                    "auth.basal.ern",
                                    "auth.basal.erp")

bresect.cohorts.ihc <- c("erp",
                         "ern",
                         "her2clinicalp",
                         "her2clinicaln",
                         "her2clinicalp.erp",
                         "her2clinicaln.erp",
                         "her2clinicalp.ern",
                         "her2clinicaln.ern")

bresect.cohorts.molecular <- c("luma",
                               "lumb",
                               "normal",
                               "her2pam50p",
                               "basal")

bresect.cohorts.ern <- c("ern",
                         "her2clinicalp.ern",
                         "her2clinicaln.ern",
                         "her2pam50p.ern",
                         "her2pam50n.ern",
                         "basal.ern",
                         "her2pam50p.her2clinicalp.ern",
                         "her2pam50p.her2clinicaln.ern")

bresect.cohorts.erp <- c("erp",
                         "her2clinicalp.erp",
                         "her2clinicaln.erp",
                         "luma",
                         "lumb",
                         "normal.erp",
                         "basal.erp",
                         "her2pam50p.erp",
                         "her2pam50n.erp",
                         "her2pam50p.her2clinicalp.erp",
                         "her2pam50p.her2clinicaln.erp")

bresect.cohorts.intclust <- paste("intclust", 1:10, sep="")

bresect.cohorts.curtis <- unique(c(bresect.cohorts.canonical, bresect.cohorts.intclust, bresect.cohorts.canonical.auth))

bresect.benchmark.name.map <- c(
    "abba 2005 (er)"="Abba 2005 (ER)",
    "alexe 2007 (lymphocytic genes)"="Alexe 2007 (lymphocytic genes)",
    "ascierto 2012 (immune 349 genes)"="Ascierto 2012 (immune 349 genes)",
    "ayers 2004 (pCR elevated)"="Ayers 2004 (pCR elevated)",
    "beck 2009 (CSF1 macrophage response)"="Beck 2009 (CSF1 macrophage)",
    "bertucci 2006 (ductal vs medullary breast cancer)"="Bertucci 2006 (ductal vs medullary)",
    "bianchini 2010 (22 genes)"="Bianchini 2010 (22 genes)",
    "biocarta IL12"="Biocarta IL12",
    "biocarta IL13"="Biocarta IL13",
    "biocarta IL2"="Biocarta IL2",
    "biocarta IL4"="Biocarta IL4",
    "bos 2009 (brain metastasis cell line)"="Bos 2009 (brain met cell line)",
    "bos 2009 (brain metastasis human)"="Bos 2009 (brain met human)",
    "carter 2006 (cin 25)"="Carter 2006 (CIN 25)",
    "carter 2006 (cin 70)"="Carter 2006 (CIN 70)",
    "chang 2004 (csr)"="Chang 2004 (CSR)",
    "chanrion 2008 (tamoxifen 36 genes)"="Chanrion 2008 (Tamoxifen 36 genes)",
    "cheang 2008 (TN prognostic predictor)"="Cheang 2008 (TN prognostic predictor)",
    "choi 2010 (quintuple negative breast cancer)"="Choi 2010 (quintuple negative)",
    "coutant 2011 (ER negative 30 genes)"="Coutant 2011 (ER- 30 genes)",
    "coutant 2011 (ER positive 39 genes)"="Coutant 2011 (ER+ 39 genes)",
    "dai 2005 (cell proliferation)"="Dai 2005 (cell proliferation)",
    "dairkee 2007 (oxidative stress)"="Dairkee 2007 (oxidative stress)",
    "der 1998 (interferon induced)"="Der 1998 (interferon induced)",
    "finak 2008 (sdpp)"="Finak 2008 (SDPP)",
    "flipits 2011 (ER positive Her2 negative PCR 11 genes)"="Filipits 2011 (ER+/HER2- PCR 11 genes)",
    "galon 2006 (immune suppression)"="Galon 2006 (immune suppression)",
    "galon 2006 (immunogenes all)"="Galon 2006 (immunogenes)",
    "galon 2006 (inflammation)"="Galon 2006 (inflammation)",
    "galon 2006 (Th1 adaptive immunity)"="Galon 2006 (Th1 adaptive immunity)",
    "glinsky 2005 (poor prognosis)"="Glinsky 2005 (poor prognosis)",
    "goldrath (immune memory)"="Goldrath (immune memory)",
    "habermann 2009 (genomic instability)"="Habermann 2009 (genomic instability)",
    "hallett 2012 (basal 14 genes)"="RBHallett 2012 (basal 14 genes)",
    "hannemann 2006 (breast cancer invasiveness)"="Hannemann 2006 (invasiveness)",
    "hess 2006 (pCR chemotherapy)"="Hess 2006 (pCR chemotherapy)",
    "hu 2009 (distant metastasis VEGF)"="Hu 2009 (distant met VEGF)",
    "juul 2010 (paclitaxel response)"="Juul 2010 (Paclitaxel response)",
    "kang 2003 (bone metastasis)"="Kang 2003 (bone met)",
    "kegg antigen processing and presentation"="KEGG Antigen Processing and Presentation",
    "khoury 2010 (her2 trastuzumab recurrence)"="Khoury 2010 (Trastuzumab resistance)",
    "khoury 2010 (her2 untreated recurrence)"="Khoury 2010 (HER2 untreated)",
    "korkola 2007 (21 genes)"="Korkola 2007 (21 genes)",
    "landemaine 2008 (lung metastasis associated)"="Landemaine 2008 (lung met associated)",
    "landemaine 2008 (lung metastasis predictor)"="Landemaine 2008 (lung met predictor)",
    "li 2009 (chemotherapy 24 genes)"="Li 2009 (chemotherapy 24 genes)",
    "lin 2010 (basal chemo 23 genes)"="Lin 2010 (basal chemo 23 genes)",
    "liu 2007 (igs)"="Liu 2007 (IGS)",
    "liu 2012 (Her2 TICS 17 genes)"="Liu 2012 (HER2 TICS 17 genes)",
    "ma 2004 (two-gene ratio)"="Ma 2004 (two-gene ratio)",
    "martin 2008 (22 genes)"="Martin 2008 (22 genes)",
    "miller 2005 (p53)"="Miller 2005 (p53)",
    "minn 2005 (lung metastasis 54 genes)"="Minn 2005 (lung met 54 genes)",
    "minn 2005 (lung metastasis 95 genes)"="Minn 2005 (lung met 95 genes)",
    "naderi 2006 (70 genes)"="Naderi 2006 (70 genes)",
    "neilson 2008"="Cheang 2008",
    "nimeus-malmstrom 2008 (local recurrence)"="Nimeus-malmstrom 2008 (local recurrence)",
    "paal 2007 (PTEN pathway activity)"="Saal 2007 (PTEN pathway)",
    "paik 2004 (oncotypedx)"="Paik 2004 (OncotypeDX)",
    "planche 2011 (normal vs tumour stroma)"="Planche 2011 (normal vs tumour stroma)",
    "rody 2009 (199 genes)"="Rody 2009 (199 genes)",
    "rody 2009 (hemopoietic cell kinase cluster)"="Rody 2009 (hemopoietic cell kinase)",
    "rody 2009 (immunoglobulin gamma cluster)"="Rody 2009 (immunoglobulin gamma)",
    "rody 2009 (interferon cluster)"="Rody 2009 (interferon)",
    "rody 2009 (lymphocyte specific kinase)"="Rody 2009 (lymphocyte specific kinase)",
    "rody 2009 (major histocompatibility class I cluster)"="Rody 2009 (MHC I)",
    "rody 2009 (major histocompatibility class II cluster)"="Rody 2009 (MHC II)",
    "rody 2009 (STAT1 cluster)"="Rody 2009 (STAT1)",
    "rody 2011 (TN good prognosis)"="Rody 2011 (TN good prognosis)",
    "rody 2011 (TN poor prognosis)"="Rody 2011 (TN poor prognosis)",
    "sabatier 2011 (Basal-like MBC)"="Sabatier 2011 (basalL MBC)",
    "sansregret 2011 (instability genes)"="Sansregret 2011 (instability)",
    "schmidt 2011 (humoral immune system)"="Schmidt 2011 (humoral immune)",
    "smeets 2010 (lymph node positive)"="Smeets 2010 (lymph node positive)",
    "smid 2006 (bone metastasis)"="Smid 2006 (bone met)",
    "sotiriou 2006 (ggi)"="Sotiriou 2006 (GGI)",
    "staff 2010 (HDPP)"="Staff 2010 (HDPP)",
    "symmans 2010 (ER related genes)"="Symmans 2010 (ER related)",
    "taube 2010 (epithelial to mesenchymal transition)"="Taube 2010 (EMT)",
    "teschendorff 2006 (t17)"="Teschendorff 2006 (t17)",
    "teschendorff 2006 (t52)"="Teschendorff 2006 (t52)",
    "teschendorff 2007 (immune response)"="Teschendorff 2007 (immune response)",
    "thuerigen 2006 (neoadjuvant chemotherapy)"="Thuerigen 2006 (neoadjuvant chemotherapy)",
    "tosolini 2001 (cluster A1 Th1 cytotoxic)"="Tosolini 2001 (A1 Th1 cytotoxic)",
    "tosolini 2001 (cluster A2 Th1)"="Tosolini 2001 (A2 Th1)",
    "tosolini 2001 (cluster B1 Th2)"="Tosolini 2001 (B1 Th2)",
    "tosolini 2001 (cluster B2 Th2)"="Tosolini 2001 (B2 Th2)",
    "tosolini 2001 (cluster B3 Th2)"="Tosolini 2001 (B3 Th2)",
    "tosolini 2001 (cluster C1 T regulatory)"="Tosolini 2001 (C1 T regulatory)",
    "tosolini 2001 (cluster C2 T regulatory Th2)"="Tosolini 2001 (C2 T regulatory Th2)",
    "tosolini 2001 (cluster D1 Th17)"="Tosolini 2001 (D1 Th17)",
    "ursini-siegel 2009 (immune 43 genes)"="Ursini-Siegel 2009 (immune 43 genes)",
    "vanlaere 2008 (IBC signature)"="Vanlaere 2008 (IBC signature)",
    "vantveer 2002 (mammaprint)"="Vantveer 2002 (MammaPrint)",
    "vanvliet 2008 (127 genes)"="Vanvliet 2008 (127 genes)",
    "wang 2005 (76 genes)"="Wang 2005 (76 genes)",
    "watkins 2009 (CD14 monocyte markers)"="Watkins 2009 (CD14 monocyte)",
    "watkins 2009 (CD19 B cell markers)"="Watkins 2009 (CD19 B cell)",
    "watkins 2009 (CD4 T helper markers)"="Watkins 2009 (CD4 T helper)",
    "watkins 2009 (CD56 NK markers)"="Watkins 2009 (CD56 NK)",
    "watkins 2009 (CD66b granulocyte markers)"="Watkins 2009 (CD66b granulocyte)",
    "watkins 2009 (CD8 cytotoxic T markers)"="Watkins 2009 (CD8 cytotoxic T)",
    "watkins 2009 (erythroblast markers)"="Watkins 2009 (erythroblast)",
    "watkins 2009 (megakaryocyte markers)"="Watkins 2009 (megakaryocyte)",
    "west 2011 (lymphocyte 8 genes)"="West 2011 (lymphocyte 8 genes)",
    "yau 2010 (TN poor outcome)"="Yau 2010 (TN poor outcome)",
    "liu 2012 (Her2-positive ER-negative 17-gene signature)"="Liu 2012 (ER-/HER2+ 17 genes)"
    )

bresect.map.classifier.names <- function(classifier.names)
{
    stopifnot(is.character(classifier.names))

    classifier.names <- sub("\\.csv$", "", basename(classifier.names))

    ifelse(classifier.names %in% names(bresect.name.map),
           paste(bresect.name.map[classifier.names], "predictor"),
           bresect.benchmark.name.map[classifier.names])
}
